### ISSUE TITLE
Add zoom buttons for desktop map

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/openjourneyplanner-ui#54]
It seems that some desktops cannot now use map zoom. Therefore, add zoom buttons if window width is desktop.

**Comment by tpievila** [comment]
Won't use width, will use http://leafletjs.com/reference.html#browser for checking touch screens.

**Comment by samuliheljo** [comment]
Bugs:
- on page: /pysakit/HSL:2434225 zoom icons are in front of stop information.

**Comment by tpievila** [comment]
@samuliheljo: Is it better to move this to different corner, move it further down on every page, or move it down only on pages with subnavigation (making the buttons move when opening/closing the subnav)?

**Comment by tpievila** [comment]
5f02dc17437d7d245925c0d77329a2c02c00f23f implemented and deployed second option.

**Comment by samuliheljo** [comment]
I added a new task into backlog for this. We need to consider:
- Zoom buttons now scroll over top bar
- Zoom buttons go over stop top header

These are not currently top priority.
